---
- name: Launch EC2 Instance
  hosts: localhost
  gather_facts: no
  vars_files:
    ec2access.yml
  
  tasks:
    - name: Create Security Group
      ec2_group:
              name: ansible_cli_SG
              description: ansible_cli_SG
              region: ap-south-1
              aws_access_key: "{{access_key}}"
              aws_secret_key: "{{secret_key}}"
              rules:
                - proto: tcp
                  from_port: 80
                  to_port: 80
                  cidr_ip: 0.0.0.0/0

                - proto: tcp
                  from_port: 22
                  to_port: 22
                  cidr_ip: 0.0.0.0/0
              rules_egress:
                - proto: all
                  cidr_ip: 0.0.0.0/0

    - name: Launch EC2
      ec2:
        key_name: AnsibleKey
        instance_type: t2.micro
        image: ami-079b5e5b3971bd10d
        wait: true
        wait_timeout: 500
        group: ansible_cli_SG
        count: 1
        vpc_subnet_id: subnet-0470bff0d475816e9
        assign_public_ip: yes
        region: ap-south-1
        state: present
        aws_access_key: "{{access_key}}"
        aws_secret_key: "{{secret_key}}"
        instance_tags:
                Name: CLI_Instance
      register: ec2out
     
    - debug:
       msg: "access Key - {{access_key}}"
